apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: navikco-publish
  namespace: kube-tekton-cd
spec:
  serviceAccountName: navikco-sa
  taskRef:
    name: navikco-publish-task
  inputs:
    resources:
      - name: git-source
        resourceRef:
          name: kube-tektoncd-github
    params:
      - name: pathToDockerFile
        value: ./setup/docker/build/Dockerfile
      - name: pathToContext
        value: git://github.com/navikco/kube-argocd.git#refs/heads/master
      - name: kubeMicroservice
        value: admin
      - name: kubeMicroserviceVersion
        value: 0.0.0_04
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: kube-tektoncd-dockerhub