apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kube-tektoncd-jib-gradle-pipeline
  namespace: kube-tekton-cd
spec:
  workspaces:
    - name: shared-workspace
  resources:
    - name: accountsRepo
      type: git
    - name: accountsImage
      type: image
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      inputs:
        resources:
          - name: accountsRepo
            type: git
      workspaces:
        - name: output
          workspace: shared-workspace
#      params:
#        - name: url
#          value: "https://github.com/navikco/kube-argocd.git"
#        - name: subdirectory
#          value: "apps/accounts"
#        - name: deleteExisting
#          value: "true"
#        - name: submodules
#          value: "false"
#        - name: depth
#          value: "2"
    - name: jib-gradle
      taskRef:
        name: jib-gradle
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: INSECUREREGISTRY
          value: "false"
      resources:
        outputs:
          - name: image
            resource: accountsImage
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kube-tektoncd-jib-gradle-pipeline-run
  namespace: kube-tekton-cd
spec:
  serviceAccountName: kube-github-admin-sa
  pipelineRef:
    name: kube-tektoncd-jib-gradle-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: jib-gradle-source-pvc
  resources:
    - name: accountsRepo
      resourceRef:
        name: kube-accounts-github
    - name: accountsImage
      resourceRef:
        name: kube-accounts-dockerhub
#    - name: build-image
#      resourceRef:
#        name: kube-accounts-dockerhub
