apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: navikco-publish-task
  namespace: kube-tekton-cd
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace
      - name: kubeMicroservice
        type: string
        description:
          Microservice Name to be Built and Published
      - name: kubeMicroserviceVersion
        type: string
        description:
          Microservice Version to be Built and Published
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.15.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
        - --build-arg=kubeMicroservice=$(inputs.params.kubeMicroservice)
        - --build-arg=kubeMicroserviceVersion=$(inputs.params.kubeMicroserviceVersion)
        - --insecure
        - --skip-tls-verify