apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kube-accounts-github
  namespace: kube-tekton-cd
spec:
  type: git
  params:
    - name: url
      value: https://github.com/navikco/kube-argocd.git
    - name: revision
      value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kube-accounts-dockerhub
  namespace: kube-tekton-cd
spec:
  type: image
  params:
    - name: url
      value: "navikco/kube:accounts"

