apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kube-tektoncd-github
  namespace: kube-tekton-cd
spec:
  type: git
  params:
    - name: url
      value: https://github.com/navikco/kube-argocd.git
    - name: revision
      value: master