apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kube-accounts-github
  namespace: kube-tekton-cd
spec:
  type: git
  params:
    - name: url
      value: https://github.com/navikco/kube-argocd.git
    - name: revision
      value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kube-accounts-dockerhub
  namespace: kube-tekton-cd
spec:
  type: image
  params:
    - name: url
      value: "navikco/kube:accounts:latest"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: accounts-publish-task
  namespace: kube-tekton-cd
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace
  outputs:
    resources:
      - name: accountsImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.15.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.accountsImage.url)
        - --context=$(inputs.params.pathToContext)
        - --build-arg=kubeMicroservice=accounts
        - --insecure
        - --skip-tls-verify
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: accounts-publish
  namespace: kube-tekton-cd
spec:
  serviceAccountName: navikco-sa
  taskRef:
    name: accounts-publish-task
  inputs:
    resources:
      - name: git-source
        resourceRef:
          name: kube-accounts-github
    params:
      - name: pathToDockerFile
        value: ./apps/accounts/src/main/resources/Dockerfile
      - name: pathToContext
        value: git://github.com/navikco/kube-argocd.git#refs/heads/master
  outputs:
    resources:
      - name: accountsImage
        resourceRef:
          name: kube-accounts-dockerhub