kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-green-admin-role-binding
  namespace: kube-green
subjects:
- kind: ServiceAccount
  name: kube-green-admin
  namespace: kube-green
roleRef:
  kind: Role
  name: kube-green-admin-role
  apiGroup: rbac.authorization.k8s.io