kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-github-admin-role
  namespace: kube-tekton-cd
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-github-admin-sa
  namespace: kube-tekton-cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-github-admin-rolebinding
  namespace: kube-tekton-cd
subjects:
  - kind: ServiceAccount
    name: kube-github-admin-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-github-admin-role