kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-github-webhook-role
  namespace: kube-tekton-cd
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - create
      - get
      - list
      - delete
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-github-webhook-sa
  namespace: kube-tekton-cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-github-webhook-rolebinding
  namespace: kube-tekton-cd
subjects:
  - kind: ServiceAccount
    name: kube-github-webhook-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-github-webhook-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-github-dockerhub-webhook-rolebinding
  namespace: kube-tekton-cd
subjects:
  - kind: ServiceAccount
    name: navikco-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-github-webhook-role